GET http://127.0.0.1:8000/api/subcategoria
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYzODI4NTEzNCwiZXhwIjoxNjM4Mjg4NzM0LCJuYmYiOjE2MzgyODUxMzQsImp0aSI6IjVaREJVS2tXMHRWNWhaTTYiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.oKfVNVqC4KlViNxEWkExwbMoBMqC6BO_2-gP1-u8gYo

###

POST http://127.0.0.1:8000/api/subcategoria
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYzODMyNDEwNSwiZXhwIjoxNjM4MzI3NzA1LCJuYmYiOjE2MzgzMjQxMDUsImp0aSI6IjhZdk1VeE82NVJEcld4RlIiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.eZyBut85vJ3zVAJZfRiG-TnWG9oybdOE0OZ9uCqRcls

{
    "nombre": "Zapato",
    "categoria_id": 2
}